baseURL = "https://EvanZimmerman307.github.io/portfolio/"
languageCode = "en-us"
title = "Evan Zimmerman"
[pagination]
  pagerSize = 10

[params]
  author = "Evan Zimmerman"
  description = "Software Engineer & ML Research — AWS Bedrock intern • UMich CSE (MS) • UVA CS (BS)."
  ShowReadingTime = true
  defaultTheme = "auto"
  disableThemeToggle = false
  showtoc = true
  ShowShareButtons = false
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  comments = false

  [params.profileMode]
    enabled = true
    title = "Hi, I'm Evan 👋"
    subtitle = "I am pursuing an MSCS at the University of Michigan, and I previously interned with AWS Bedrock as an SDE on the Anthropic model hosting team. I am passionate about the intersection of ML/AI and distributed systems. I enjoy working on ambiguous problems that push me to develop new skills."
    imageUrl = "image/Zimmerman_Evan_Headshot.jpg"
    imageWidth = 290
    imageHeight = 360

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/EvanZimmerman307"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/evan-zimmerman-3817541aa"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:evanzimm@umich.edu"
  
  [[params.profileMode.buttons]]
    name = "Projects"
    url = "/portfolio/projects/"

    [[params.profileMode.buttons]]
    name = "About Me"
    url = "/portfolio/aboutme/"

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 10
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 20
  [[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 30
  [[menu.main]]
    name = "Education"
    url = "/education/"
    weight = 40
  [[menu.main]]
    name = "About Me"
    url = "/aboutme/"
    weight = 50

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
