
baseURL = "https://<your-username>.github.io/<your-repo>/"
languageCode = "en-us"
title = "Evan Zimmerman"
theme = "PaperMod"
paginate = 10

[params]
  author = "Evan Zimmerman"
  description = "Software Engineer & ML Research — AWS Bedrock intern • UMich CSE (MS) • UVA CS (BS)."
  ShowReadingTime = true
  defaultTheme = "auto"
  disableThemeToggle = false
  showtoc = true
  ShowShareButtons = false
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  comments = false

  [params.homeInfoParams]
    Title = "Hi, I'm Evan 👋"
    Content = "I build scalable systems and practical ML. Currently MS CSE @ UMich; previously AWS Bedrock intern on model hosting and observability.\nExplore my work, research, and projects below."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/EvanZimmerman307"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/evan-zimmerman-3817541aa"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:evanzimm@umich.edu"

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 10
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 20
  [[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 30
  [[menu.main]]
    name = "Education"
    url = "/education/"
    weight = 40
  [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 50

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
